import Worker from "../models/Worker.js";
import Customer from "../models/Customer.js";
import { getCookieOptions, sanitizeUser } from "./authController.js";
import { deleteFromCloudinary } from "../utils/cloudinary.js";

// POST /api/auth/worker/register
export const registerWorker = async (req, res, next) => {
  try {
    const {
      fullName,
      phoneNumber,
      dateOfBirth,
      gender,
      aadhaarNumber,
      address,
      pincode,
      subdivision,
      city,
      state,
      serviceCharge,
      occupation,
      profileImage,
      aadhaarImage,
    } = req.body;

    const existingWorker = await Worker.findOne({
      $or: [{ phoneNumber }, { aadhaarNumber: aadhaarNumber.replace(/\D/g, "") }],
    });

    if (existingWorker) {
      const duplicateField = existingWorker.phoneNumber === phoneNumber ? "phone number" : "Aadhaar number";
      return res.status(409).json({
        success: false,
        message: `A worker with this ${duplicateField} is already registered`,
      });
    }

    const existingCustomer = await Customer.findOne({ phoneNumber });
    if (existingCustomer) {
      return res.status(409).json({
        success: false,
        message: "This phone number is already registered as a customer. Please use a different number.",
      });
    }

    // Generate Auto Password: Birth Year (4 digits) + Last 4 digits of Aadhaar (4 digits)
    const dobObj = new Date(dateOfBirth);
    const birthYear = dobObj.getFullYear();
    const cleanAadhaar = aadhaarNumber.replace(/\D/g, "");
    const last4Aadhaar = cleanAadhaar.slice(-4);
    const autoGeneratedPassword = `${birthYear}${last4Aadhaar}`;

    const worker = await Worker.create({
      fullName,
      phoneNumber,
      dateOfBirth: new Date(dateOfBirth),
      gender,
      aadhaarNumber: aadhaarNumber.replace(/\D/g, ""),
      password: autoGeneratedPassword,
      address,
      pincode,
      subdivision,
      city: city || "",
      state: state || "",
      serviceCharge: Number(serviceCharge),
      occupation,
      profileImage: profileImage || "",
      aadhaarImage: aadhaarImage || "",
    });

    const accessToken = worker.generateAccessToken();

    return res
      .status(201)
      .cookie("accessToken", accessToken, getCookieOptions())
      .json({
        success: true,
        message: "Worker registered successfully",
        data: {
          generatedPassword: autoGeneratedPassword
        },
      });
  } catch (error) {
    const { profileImage, aadhaarImage } = req.body;
    if (profileImage) await deleteFromCloudinary(profileImage);
    if (aadhaarImage) await deleteFromCloudinary(aadhaarImage);
    next(error);
  }
};

// POST /api/auth/customer/register
export const registerCustomer = async (req, res, next) => {
  try {
    const {
      fullName,
      phoneNumber,
      email,
      password,
      address,
      pincode,
      subdivision,
      city,
      state,
      profileImage,
    } = req.body;

    const existingCustomer = await Customer.findOne({
      $or: [{ phoneNumber }, { email: email.toLowerCase() }],
    });

    if (existingCustomer) {
      const duplicateField = existingCustomer.phoneNumber === phoneNumber ? "phone number" : "email";
      return res.status(409).json({
        success: false,
        message: `A customer with this ${duplicateField} is already registered`,
      });
    }

    const existingWorker = await Worker.findOne({ phoneNumber });
    if (existingWorker) {
      return res.status(409).json({
        success: false,
        message: "This phone number is already registered as a worker. Please use a different number.",
      });
    }

    const customer = await Customer.create({
      fullName,
      phoneNumber,
      email: email.toLowerCase(),
      password,
      address,
      pincode,
      subdivision,
      city: city || "",
      state: state || "",
      profileImage: profileImage || "",
    });

    const accessToken = customer.generateAccessToken();

    return res
      .status(201)
      .cookie("accessToken", accessToken, getCookieOptions())
      .json({
        success: true,
        message: "Customer registered successfully",
      });
  } catch (error) {
    const { profileImage } = req.body;
    if (profileImage) await deleteFromCloudinary(profileImage);
    next(error);
  }
};
